In [31]:
# Import libraries

import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from patsy import dmatrix
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
# Pretty display for notebooks

%matplotlib inline


# Allows the use of display() for DataFrames
from IPython.display import display 

# Ignore the warnings
import warnings
warnings.filterwarnings('ignore')

# Load the dataset
train = pd.read_csv("../asset/train.csv")
test = pd.read_csv("../asset/test.csv")
weather = pd.read_csv("../asset/weather.csv")
key = pd.read_csv("../asset/key.csv")
submission_example = pd.read_csv("../asset/sampleSubmission.csv")

# Success - Display the first record


import pickle
import awesome_functions as cf

# 원본을 유지하기 위해서 카피
df_train = train.copy()
df_weather = weather.copy()
df_key = key.copy()
df_test = test.copy()
df_submission = submission_example.copy()

In [30]:
df_test.shape

(526917, 3)

In [32]:
df_submission.shape

(526917, 2)

In [36]:
df_submission.head()

id  units
0  2_1_2013-04-01      0
1  2_2_2013-04-01      0
2  2_3_2013-04-01      0
3  2_4_2013-04-01      0
4  2_5_2013-04-01      0

In [67]:
total = total.drop("Unnamed: 0", axis = 1)

In [73]:
merge_weather = pd.read_csv("weather_2.0_final_201807051335.csv")

In [76]:
def addIsWeekend(data):
    if data >= 5:
        return 1
    else:
        return 0

In [77]:
merge_weather["is_weekend"] = merge_weather["weekday"].apply(addIsWeekend)

In [80]:
df_test = test.copy()
df_test = df_test.merge(df_key, on="store_nbr")
df_test = df_test.merge(merge_weather, on=["date", "station_nbr"])

In [81]:
df_test

date  store_nbr  item_nbr  station_nbr  tmax  tmin  tavg  \
0       2013-04-01          2         1           14    71    42    56   
1       2013-04-01          2         2           14    71    42    56   
2       2013-04-01          2         3           14    71    42    56   
3       2013-04-01          2         4           14    71    42    56   
4       2013-04-01          2         5           14    71    42    56   
5       2013-04-01          2         6           14    71    42    56   
6       2013-04-01          2         7           14    71    42    56   
7       2013-04-01          2         8           14    71    42    56   
8       2013-04-01          2         9           14    71    42    56   
9       2013-04-01          2        10           14    71    42    56   
10      2013-04-01          2        11           14    71    42    56   
11      2013-04-01          2        12           14    71    42    56   
12      2013-04-01          2        13           14    71    42    56   
13      2013-04-01          2        14           14    71    42    56   
14      2013-04-01          2        15           14    71    42    56   
15      2013-04-01          2        16           14    71    42    56   
16      2013-04-01          2        17           14    71    42    56   
17      2013-04-01          2        18           14    71    42    56   
18      2013-04-01          2        19           14    71    42    56   
19      2013-04-01          2        20           14    71    42    56   
20      2013-04-01          2        21           14    71    42    56   
21      2013-04-01          2        22           14    71    42    56   
22      2013-04-01          2        23           14    71    42    56   
23      2013-04-01          2        24           14    71    42    56   
24      2013-04-01          2        25           14    71    42    56   
25      2013-04-01          2        26           14    71    42    56   
26      2013-04-01          2        27           14    71    42    56   
27      2013-04-01          2        28           14    71    42    56   
28      2013-04-01          2        29           14    71    42    56   
29      2013-04-01          2        30           14    71    42    56   
...            ...        ...       ...          ...   ...   ...   ...   
526887  2014-08-02         40        82           13    81    51    66   
526888  2014-08-02         40        83           13    81    51    66   
526889  2014-08-02         40        84           13    81    51    66   
526890  2014-08-02         40        85           13    81    51    66   
526891  2014-08-02         40        86           13    81    51    66   
526892  2014-08-02         40        87           13    81    51    66   
526893  2014-08-02         40        88           13    81    51    66   
526894  2014-08-02         40        89           13    81    51    66   
526895  2014-08-02         40        90           13    81    51    66   
526896  2014-08-02         40        91           13    81    51    66   
526897  2014-08-02         40        92           13    81    51    66   
526898  2014-08-02         40        93           13    81    51    66   
526899  2014-08-02         40        94           13    81    51    66   
526900  2014-08-02         40        95           13    81    51    66   
526901  2014-08-02         40        96           13    81    51    66   
526902  2014-08-02         40        97           13    81    51    66   
526903  2014-08-02         40        98           13    81    51    66   
526904  2014-08-02         40        99           13    81    51    66   
526905  2014-08-02         40       100           13    81    51    66   
526906  2014-08-02         40       101           13    81    51    66   
526907  2014-08-02         40       102           13    81    51    66   
526908  2014-08-02         40       103           13    81    51    66   
526909  2014-08-02

In [58]:
df_test_copy.columns

Index(['date', 'store_nbr', 'item_nbr', 'station_nbr'], dtype='object')

In [59]:
total.columns

Index(['Unnamed: 0', 'date', 'store_nbr', 'item_nbr', 'units', 'log1p',
       'date2', 'station_nbr', 'preciptotal_flag', 'depart_flag', 'weekday',
       'is_weekend', 'is_holiday', 'is_holiday_weekday', 'is_holiday_weekend',
       'day', 'month', 'year', 'holiday_name', 'around_BlackFriday', 'tmax',
       'tmin', 'tavg', 'depart', 'dewpoint', 'wetbulb', 'heat', 'cool',
       'preciptotal', 'stnpressure', 'resultspeed', 'resultdir', 'avgspeed'],
      dtype='object')

In [57]:
df_test_copy.merge(total, on=["date", "station_nbr"])

Empty DataFrame
Columns: [date, store_nbr_x, item_nbr_x, station_nbr, Unnamed: 0, store_nbr_y, item_nbr_y, units, log1p, date2, preciptotal_flag, depart_flag, weekday, is_weekend, is_holiday, is_holiday_weekday, is_holiday_weekend, day, month, year, holiday_name, around_BlackFriday, tmax, tmin, tavg, depart, dewpoint, wetbulb, heat, cool, preciptotal, stnpressure, resultspeed, resultdir, avgspeed]
Index: []

[0 rows x 35 columns]

In [43]:
df_test_copy.dtypes

date           object
store_nbr       int64
item_nbr        int64
station_nbr     int64
dtype: object

In [3]:
total = pd.read_csv("total.csv")

In [4]:
total.shape

(229230, 33)

In [5]:
total.columns

Index(['Unnamed: 0', 'date', 'store_nbr', 'item_nbr', 'units', 'log1p',
       'date2', 'station_nbr', 'preciptotal_flag', 'depart_flag', 'weekday',
       'is_weekend', 'is_holiday', 'is_holiday_weekday', 'is_holiday_weekend',
       'day', 'month', 'year', 'holiday_name', 'around_BlackFriday', 'tmax',
       'tmin', 'tavg', 'depart', 'dewpoint', 'wetbulb', 'heat', 'cool',
       'preciptotal', 'stnpressure', 'resultspeed', 'resultdir', 'avgspeed'],
      dtype='object')

In [6]:
total.head()

Unnamed: 0        date  store_nbr  item_nbr  units     log1p       date2  \
0           0  2012-01-01          1         9     29  3.401197  2012-01-01   
1           1  2012-01-01          1        28      2  1.098612  2012-01-01   
2           2  2012-01-01          1        40      0  0.000000  2012-01-01   
3           3  2012-01-01          1        47      0  0.000000  2012-01-01   
4           4  2012-01-01          1        51      1  0.693147  2012-01-01   

   station_nbr  preciptotal_flag  depart_flag   ...     depart  dewpoint  \
0            1               0.0          0.0   ...         11        36   
1            1               0.0          0.0   ...         11        36   
2            1               0.0          0.0   ...         11        36   
3            1               0.0          0.0   ...         11        36   
4            1               0.0          0.0   ...         11        36   

   wetbulb  heat  cool  preciptotal  stnpressure  resultspeed resultdir  \
0       40    24     0         0.05        29.78          3.6      20.0   
1       40    24     0         0.05        29.78          3.6      20.0   
2       40    24     0         0.05        29.78          3.6      20.0   
3       40    24     0         0.05        29.78          3.6      20.0   
4       40    24     0         0.05        29.78          3.6      20.0   

  avgspeed  
0      4.6  
1      4.6  
2      4.6  
3      4.6  
4      4.6  

[5 rows x 33 columns]

In [7]:
total["is_weekend"].unique()

array([1, 0])

In [8]:
model = sm.OLS.from_formula("log1p ~ C(item_nbr):scale(cool)+ C(item_nbr):scale(heat) + C(item_nbr):scale(preciptotal) + C(item_nbr):scale(depart) + C(item_nbr):C(is_weekend) + 0", data=total)

In [9]:
result = model.fit()

In [10]:
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                  log1p   R-squared:                       0.858
Model:                            OLS   Adj. R-squared:                  0.858
Method:                 Least Squares   F-statistic:                     2142.
Date:                Fri, 06 Jul 2018   Prob (F-statistic):               0.00
Time:                        10:16:52   Log-Likelihood:            -2.3172e+05
No. Observations:              229230   AIC:                         4.647e+05
Df Residuals:                  228582   BIC:                         4.714e+05
Df Model:                         647                                         
Covariance Type:            nonrobust                                         
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
C(

In [23]:
matrix_df = pd.DataFrame(dmatrix("C(item_nbr):scale(cool)+ C(item_nbr):scale(heat) + C(item_nbr):scale(preciptotal) + C(item_nbr):scale(depart) + C(item_nbr):C(is_weekend) + 0", data=total))

In [86]:
matrix_df.columns

RangeIndex(start=0, stop=648, step=1)

In [141]:
len(total[total["store_nbr"] == 35])

0

In [87]:
df_test.columns

Index(['date', 'store_nbr', 'item_nbr', 'station_nbr', 'tmax', 'tmin', 'tavg',
       'depart', 'dewpoint', 'wetbulb', 'heat', 'cool', 'preciptotal',
       'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed',
       'year', 'month', 'day', 'weekday', 'holiday', 'is_weekend'],
      dtype='object')

In [105]:
matrix_df = pd.DataFrame(dmatrix("C(item_nbr):scale(cool) + 0", data=total))

In [110]:
for i in range(1, 112):
    if i not in sorted(total["item_nbr"].unique()):
        print(i)

24
63
66


In [115]:
item_24 = df_train[df_train["item_nbr"] == 24]

In [117]:
item_63 = df_train[df_train["item_nbr"] == 63]

In [119]:
item_66 = df_train[df_train["item_nbr"] == 66]

In [116]:
item_24[item_24["units"] > 0]["store_nbr"].unique()

array([35])

In [118]:
item_63[item_63["units"] > 0]["store_nbr"].unique()

array([35])

In [120]:
item_66[item_66["units"] > 0]["store_nbr"].unique()

array([35])

In [122]:
test_item_24 = df_test[df_test["item_nbr"] == 24]

In [134]:
store_nbr_2 = train[(train["store_nbr"] == 2) & (train["item_nbr"] == 1)]

In [138]:
store_nbr_2[store_nbr_2["date"] == "2013-04-01"]

Empty DataFrame
Columns: [date, store_nbr, item_nbr, units]
Index: []

In [133]:
df_test

date  store_nbr  item_nbr  station_nbr  tmax  tmin  tavg  \
0       2013-04-01          2         1           14    71    42    56   
1       2013-04-01          2         2           14    71    42    56   
2       2013-04-01          2         3           14    71    42    56   
3       2013-04-01          2         4           14    71    42    56   
4       2013-04-01          2         5           14    71    42    56   
5       2013-04-01          2         6           14    71    42    56   
6       2013-04-01          2         7           14    71    42    56   
7       2013-04-01          2         8           14    71    42    56   
8       2013-04-01          2         9           14    71    42    56   
9       2013-04-01          2        10           14    71    42    56   
10      2013-04-01          2        11           14    71    42    56   
11      2013-04-01          2        12           14    71    42    56   
12      2013-04-01          2        13           14    71    42    56   
13      2013-04-01          2        14           14    71    42    56   
14      2013-04-01          2        15           14    71    42    56   
15      2013-04-01          2        16           14    71    42    56   
16      2013-04-01          2        17           14    71    42    56   
17      2013-04-01          2        18           14    71    42    56   
18      2013-04-01          2        19           14    71    42    56   
19      2013-04-01          2        20           14    71    42    56   
20      2013-04-01          2        21           14    71    42    56   
21      2013-04-01          2        22           14    71    42    56   
22      2013-04-01          2        23           14    71    42    56   
23      2013-04-01          2        24           14    71    42    56   
24      2013-04-01          2        25           14    71    42    56   
25      2013-04-01          2        26           14    71    42    56   
26      2013-04-01          2        27           14    71    42    56   
27      2013-04-01          2        28           14    71    42    56   
28      2013-04-01          2        29           14    71    42    56   
29      2013-04-01          2        30           14    71    42    56   
...            ...        ...       ...          ...   ...   ...   ...   
526887  2014-08-02         40        82           13    81    51    66   
526888  2014-08-02         40        83           13    81    51    66   
526889  2014-08-02         40        84           13    81    51    66   
526890  2014-08-02         40        85           13    81    51    66   
526891  2014-08-02         40        86           13    81    51    66   
526892  2014-08-02         40        87           13    81    51    66   
526893  2014-08-02         40        88           13    81    51    66   
526894  2014-08-02         40        89           13    81    51    66   
526895  2014-08-02         40        90           13    81    51    66   
526896  2014-08-02         40        91           13    81    51    66   
526897  2014-08-02         40        92           13    81    51    66   
526898  2014-08-02         40        93           13    81    51    66   
526899  2014-08-02         40        94           13    81    51    66   
526900  2014-08-02         40        95           13    81    51    66   
526901  2014-08-02         40        96           13    81    51    66   
526902  2014-08-02         40        97           13    81    51    66   
526903  2014-08-02         40        98           13    81    51    66   
526904  2014-08-02         40        99           13    81    51    66   
526905  2014-08-02         40       100           13    81    51    66   
526906  2014-08-02         40       101           13    81    51    66   
526907  2014-08-02         40       102           13    81    51    66   
526908  2014-08-02         40       103           13    81    51    66   
526909  2014-08-02

In [106]:
matrix_df.columns

RangeIndex(start=0, stop=108, step=1)

In [103]:
matrix_df_test = pd.DataFrame(dmatrix("C(item_nbr):scale(cool) + 0", data=df_test))

In [104]:
matrix_df_test.columns

RangeIndex(start=0, stop=111, step=1)

In [82]:
matrix_df_test = pd.DataFrame(dmatrix("C(item_nbr):scale(cool)+ C(item_nbr):scale(heat) + C(item_nbr):scale(preciptotal) + C(item_nbr):scale(depart) + C(item_nbr):C(is_weekend) + 0", data=df_test))

In [100]:
len(total["cool"].unique())

36

In [98]:
len(total["cool"].unique()) + len(total["heat"].unique()) + len(total["preciptotal"].unique()) + len(total["depart"].unique())

407

In [95]:
len(df_test["cool"].unique()) + len(df_test["heat"].unique()) + len(df_test["preciptotal"].unique()) + len(df_test["depart"].unique())

381

In [24]:
model = linear_model.Lasso(alpha = 0.01)

In [25]:
result = model.fit(matrix_df_test, total["log1p"])

In [26]:
result.score(matrix_df,total["log1p"])

0.6842481055650032

In [99]:
ynew = model.predict()

TypeError: predict() missing 1 required positional argument: 'X'

In [27]:
cv = KFold(10)

In [28]:
kfold = cross_val_score(result,matrix_df,total["log1p"], scoring="r2", cv=cv)

In [29]:
kfold, kfold.mean()

(array([0.81270983, 0.56045926, 0.58906582, 0.50703572, 0.79559728,
        0.63467041, 0.62473362, 0.82614631, 0.41730078, 0.34265746]),
 0.6110376502470306)